/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Criteria to select the source entity (by Name or Context).
 */
export type Selector = {
  /**
   * Entity Name (e.g., 'Project').
   */
  name?: string;
  /**
   * Semantic Context URI (e.g., 'http://schema.org/ResearchProject').
   */
  context?: string;
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
/**
 * Criteria to select the target entity.
 */
export type Selector1 = {
  /**
   * Entity Name (e.g., 'Project').
   */
  name?: string;
  /**
   * Semantic Context URI (e.g., 'http://schema.org/ResearchProject').
   */
  context?: string;
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};

/**
 * Schema for defining transformation rules between two logical data models.
 */
export interface LogicalDataModelMappingDefinitionSchema {
  /**
   * Unique identifier for this mapping configuration.
   */
  mapping_id: string;
  /**
   * Human-readable description of the mapping purpose.
   */
  description?: string;
  /**
   * Name of the source data model (must match model_name in source YAML).
   */
  source_model: string;
  /**
   * Name of the target data model (must match model_name in target YAML).
   */
  target_model: string;
  /**
   * List of mapping rules for entities.
   */
  entity_mappings: EntityMapping[];
  [k: string]: unknown;
}
/**
 * Mapping rule between a source entity and a target entity.
 */
export interface EntityMapping {
  source_selector: Selector;
  target_selector: Selector1;
  /**
   * Note about this specific entity mapping.
   */
  description?: string;
  /**
   * Rules for mapping attributes within this entity.
   */
  attribute_mappings?: AttributeMapping[];
  /**
   * Rules for mapping relationships originating from this entity.
   */
  relationship_mappings?: RelationshipMapping[];
  [k: string]: unknown;
}
export interface AttributeMapping {
  /**
   * Name of the attribute in the source entity.
   */
  source_attribute: string;
  /**
   * Name of the attribute in the target entity. Required unless rule is 'ignore'.
   */
  target_attribute?: string;
  /**
   * Dot-notation path for nested structures (e.g., 'has_access_right.access_type'). Use this when mapping a flat attribute to a related entity's attribute.
   */
  target_path?: string;
  /**
   * Transformation rule type.
   */
  rule?: 'direct_copy' | 'static_value' | 'map_values' | 'ignore';
  /**
   * Fixed value to use when rule is 'static_value'.
   */
  static_value?: string | number | boolean | null;
  /**
   * Key-value pairs for translating enum values (Source Value -> Target Value).
   */
  value_map?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
export interface RelationshipMapping {
  /**
   * Name of the relationship in the source entity.
   */
  source_relationship: string;
  /**
   * Name of the relationship in the target entity.
   */
  target_relationship: string;
  /**
   * Indicates if the relationship direction is inverted in the target model.
   */
  direction?: 'same' | 'inverse';
  /**
   * Description of relationship mapping logic.
   */
  description?: string;
  [k: string]: unknown;
}
