/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for logical data models allowing split files (Master definition and Entity fragments).
 */
export type LogicalDataModelModularSchema =
  | {
      schema_version: SchemaVersion;
      model_name: ModelName;
      description?: Description;
      entities?: Entities;
      [k: string]: unknown;
    }
  | {
      schema_version?: SchemaVersion;
      model_name?: ModelName;
      description?: Description;
      entities: Entities;
      [k: string]: unknown;
    };
/**
 * Version of this schema definition.
 */
export type SchemaVersion = '1.0';
/**
 * Unique name for the data model.
 */
export type ModelName = string;
/**
 * Description text.
 */
export type Description = string;

/**
 * Collection of entities.
 */
export interface Entities {
  [k: string]: Entity;
}
/**
 * This interface was referenced by `Entities`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Z][a-zA-Z0-9]*$".
 */
export interface Entity {
  description: Description;
  attributes: {
    [k: string]: Attribute;
  };
  relationships?: {
    [k: string]: Relationship;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 */
export interface Attribute {
  /**
   * Data type.
   */
  type: 'String' | 'Integer' | 'Float' | 'Boolean' | 'Date' | 'DateTime' | 'Text' | 'Enum';
  description: Description;
  required?: boolean;
  primary_key?: boolean;
  note?: string;
  options?: string[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 */
export interface Relationship {
  /**
   * Target Entity Name
   */
  target: string;
  description?: Description;
  cardinality: '1:1' | '1:N' | '0:1' | '0:N' | 'N:M';
  /**
   * Edge properties.
   */
  attributes?: {
    [k: string]: Attribute;
  };
  [k: string]: unknown;
}
